### ISSUE TITLE
[Teams][Web] 500 at searching teams

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#269]
Google Chrome Version 66.0.3359.181
Pre-conditions: 

Steps to reproduce:

1. Log in to the web app as super admin/country admin
2. Search for teamsURL | http://40.115.37.120:50000/api/v1/teams/web?country=UA&superadmin=true
3. Check results 

Expected result: there is teams list 
Actual result: there is no any team, request is returned with 500 error http://take.ms/aheV9

**Comment by Dasha1990** [comment]
After merging PR https://github.com/letsdoitworld/World-Cleanup-Day/pull/271
super admin can see teams list and search for teams
And we got 500 error at opening team details 

  | GET /api/v1/teams/3b61c81a-2b8e-11e8-b467-0ed5f89f719nf HTTP/1.1
-- | --

returns 500 
[{
	"code": "API_UNEXPECTED_ERROR",
	"message": "An unexpected error has occured."
}]
http://take.ms/PIEI3

**Comment by Dasha1990** [comment]
Server logs:
api_1      | 2018-06-06T14:22:40.909Z - debug: SENECA: [SEND] role:db,cmd:getTeam ["role:db,cmd:getTeam",{"id":"3b61c81a-2b8e-11e8-b467-0ed5f89f718x","__":{"user":{},"session":{}}}]
db_1       | 2018-06-06T14:22:40.935Z - debug: SENECA: [ENTER] role:db,cmd:getTeam {"id":"3b61c81a-2b8e-11e8-b467-0ed5f89f718x","__":{"user":{},"session":{}},"role":"db","cmd":"getTeam","transport$":{"track":["d2wvmhat5rzt/1528294822468/356/3.4.1/-"],"origin":"d2wvmhat5rzt/1528294822468/356/3.4.1/-","time":{"client_sent":"1528294960911"}},"id$":"4bw46njlblo3/hvyki613kl2e","fatal$":false,"tx$":"hvyki613kl2e"}
db_1       | 2018-06-06T14:22:40.962Z - fatal: SENECA: [CRASH] role:db,cmd:getTeam {"id":"3b61c81a-2b8e-11e8-b467-0ed5f89f718x","role":"db","cmd":"getTeam","transport$":{"track":["d2wvmhat5rzt/1528294822468/356/3.4.1/-"],"origin":"d2wvmhat5rzt/1528294822468/356/3.4.1/-","time":{"client_sent":"1528294960911"}},"id$":"4bw46njlblo3/hvyki613kl2e","fatal$":false,"tx$":"hvyki613kl2e"} // Error: Unknown message code 'undefined'.
couchdb_1  | [info] [<0.860.0>] 172.18.0.4 - - GET /teams/_design/all/_view/view?key=%223b61c81a-2b8e-11e8-b467-0ed5f89f718x%22&sorted=false&limit=1 200
db_1       |     at new Constructor (/module-lucius/error/exception.js:12:15)
api_1      | 2018-06-06T14:22:40.970Z - error: Error: 
api_1      |     at module.exports.internals.Utils.internals.Utils.handle_response (/module-service-factory/node_modules/seneca-transport/lib/transport-utils.js:71:11)
api_1      |     at /module-service-factory/node_modules/seneca-transport/lib/http.js:154:25
api_1      |     at internals.Client._shortcut.callback.request.read (/module-service-factory/node_modules/seneca-transport/node_modules/wreck/lib/index.js:514:20)
api_1      |     at finish (/module-service-factory/node_modules/seneca-transport/node_modules/wreck/lib/index.js:360:16)
api_1      |     at wrapped (/module-service-factory/node_modules/hoek/lib/index.js:871:20)
api_1      |     at module.exports.internals.Recorder.onReaderFinish (/module-service-factory/node_modules/seneca-transport/node_modules/wreck/lib/index.js:406:16)
api_1      |     at Object.onceWrapper (events.js:314:30)
api_1      |     at emitNone (events.js:110:20)
api_1      |     at module.exports.internals.Recorder.emit (events.js:207:7)
api_1      |     at finishMaybe (_stream_writable.js:579:14)
api_1      |     at afterWrite (_stream_writable.js:431:3)
api_1      | 2018-06-06T14:22:40.971Z - warning: Error undefined was masked in the API response as API_UNEXPECTED_ERROR.
api_1      | 2018-06-06T14:22:40.974Z - HTTP: [RESP] 178.151.244.234 GET /api/v1/teams/3b61c81a-2b8e-11e8-b467-0ed5f89f718x 500 78 - 63.820 ms
db_1       |     at Connector.<anonymous> (/src/plugins/teams.js:68:46)
db_1       |     at <anonymous>
db_1       |     at process._tickCallback (internal/process/next_tick.js:169:7)
